version: '3'
services:
  app:
    build: .
    ports:
      - "3011:3011"
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  server:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
volumes:
  ./src:        