version: '3.3'

services:
  vue-app:
    build: .
    ports:
      - "3011:3011" # Vue aplikacija
      - "5000:5000" # JSON-server
    volumes:
      - jobs-data:/app/src # Montiramo jobs.json kao volumen
    
volumes:
  jobs-data:    
