version: '3'
services:
  app:
    build: .
    ports:
      - "3011:3011"
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - ./src/jobs.json:/app/src/jobs.json

  server:
    build: .
    command: npm run server --port 5000
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./src/jobs.json:/app/src/jobs.json