version: '3'
services:
  vue-app:
    build:
      context: .
    networks:
      - app-network  # Povezivanje Vue aplikacije s Nginx mrežom
    expose:
      - "3000"  # Izlažemo port za internu komunikaciju unutar mreže

  json-server:
    image: json-server:latest
    volumes:
      - ./jobs.json:/jobs.json  # Ako koristite svoj db.json
    command: json-server --watch /jobs.json --port 5000  # Pokreni json-server na portu 5000
    networks:
      - app-network  # Povezivanje json-servera s Nginx mrežom
    expose:
      - "5000"  # Samo za internu komunikaciju unutar mreže

networks:
  app-network:
    driver: bridge