version: '3.3'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Vue aplikacija
      - "5000:5000" # JSON-server
    volumes:
      - ./src/jobs.json:/app/src/jobs.json # Montiramo jobs.json kao volumen
    restart: always
